// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://btsfqgindxfyjxtdhqwc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJ0c2ZxZ2luZHhmeWp4dGRocXdjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzYzOTcxMjcsImV4cCI6MjA1MTk3MzEyN30.51nwt2kfgnu3PBgQHp9rzvhil5kPNBabPt5PL-QuJRI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);